import type { InventoryItem } from "./types";

export const masterData: InventoryItem[] = [
  {
    id: 1,
    channel: "Meesho",
    type: "B2C",
    name: "Baby Diapers NB (72 Pcs)",
    price: 699,
    shipping: 65,
    commission: 105,
    stock_kol: 40,
    stock_pith: 50,
    stock_har: 20,
    stock_blr: 10,
    stock_unalloc: 100,
    stock_factory: 200,
    stock_wip: 500,
    drr_kol: 10,
    drr_pith: 2,
    drr_har: 1,
    drr_blr: 2,
    drr: 15,
    spend: 1200,
    orders: 12,
    returns: 1,
    impr: 15000,
    clicks: 300,
    ads_active: true,
    rating: 4.2,
    reviews: 150,
  },
  {
    id: 101,
    channel: "Amazon",
    type: "B2C",
    name: "Baby Diapers NB (72 Pcs)",
    price: 749,
    shipping: 85,
    commission: 120,
    stock_kol: 30,
    stock_pith: 30,
    stock_har: 30,
    stock_blr: 30,
    stock_unalloc: 50,
    stock_factory: 0,
    stock_wip: 0,
    drr_kol: 10,
    drr_pith: 5,
    drr_har: 5,
    drr_blr: 5,
    drr: 25,
    spend: 2000,
    orders: 18,
    returns: 2,
    impr: 25000,
    clicks: 600,
    ads_active: true,
    rating: 3.8,
    reviews: 85,
  },
  {
    id: 2,
    channel: "Amazon",
    type: "B2C",
    name: "Herbal Tea Infusion (100g)",
    price: 349,
    shipping: 50,
    commission: 52,
    stock_kol: 150,
    stock_pith: 200,
    stock_har: 80,
    stock_blr: 90,
    stock_unalloc: 300,
    stock_factory: 500,
    stock_wip: 100,
    drr_kol: 20,
    drr_pith: 15,
    drr_har: 10,
    drr_blr: 12,
    drr: 57,
    spend: 2500,
    orders: 40,
    returns: 2,
    impr: 40000,
    clicks: 800,
    ads_active: true,
    rating: 4.8,
    reviews: 320,
  },
  {
    id: 3,
    channel: "Meesho",
    type: "B2C",
    name: "Organic Cotton Tote Bag",
    price: 499,
    shipping: 60,
    commission: 75,
    stock_kol: 5,
    stock_pith: 8,
    stock_har: 2,
    stock_blr: 3,
    stock_unalloc: 10,
    stock_factory: 50,
    stock_wip: 20,
    drr_kol: 2,
    drr_pith: 1,
    drr_har: 0,
    drr_blr: 1,
    drr: 4,
    spend: 500,
    orders: 5,
    returns: 0,
    impr: 5000,
    clicks: 100,
    ads_active: false,
    rating: 4.5,
    reviews: 45,
  },
];
